name: dataproc_serverless_poc
description: ''
version: '1.0'
author: shashank@prophecy.io
language: python
buildSystem: ''
buildSystemDetails:
  artefactID: dataprocserverlesspoc
  parentArtefactID: shashankprophecyioteam
  buildSystem: wheel
  author: null
  createdAt: '2024-09-16 14:02:56'
pipelines:
  pipelines/customer_test:
    name: customer_test
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: python
    createdAt: '2024-09-16 14:02:56'
    datasets:
      inputs:
      - datasets/customer_read
      outputs:
      - datasets/customer_write
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_read:
    name: customer_read
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-09-16 14:03:26'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2512
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-09-16 14:03:26'
  datasets/customer_write:
    name: customer_write
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-09-16 14:04:57'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 2512
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-09-16 14:04:57'
templates: {}
jobs: {}
gemContainer:
  languageVersion: '3.10'
  gemLibsVersion: 1.3.4.0
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-09-16 14:02:56'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-09-16T14:02:56.387408Z'
  name: plibMaven
  version: 8.2.0-SNAPSHOT
  id: '98224999'
  createdAt: '2024-09-16T14:02:56.387408Z'
  type: plibMaven
- modifiedAt: '2024-09-16T14:02:56.387408Z'
  name: plibPypi
  version: 1.9.16
  id: '1304596238'
  createdAt: '2024-09-16T14:02:56.387408Z'
  type: plibPypi
projectDependencies:
  '224':
    projectUID: 224
    projectName: ProphecySparkBasicsPython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_224.git&subPath=
    version: 0.2.28.dev6
    isDefault: true
    author: null
    createdAt: '2024-09-16 14:02:38'
  '225':
    projectUID: 225
    projectName: ProphecyWarehousePython
    repositoryPath: gitUri=http://gitserver:3000/wDp16mGH_team_30/QWF0O8MX_project_225.git&subPath=
    version: 0.0.8
    isDefault: true
    author: null
    createdAt: '2024-09-16 14:02:38'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
