name: dataproc-serverless-poc-scala
description: ''
version: 0.0.1
author: shashank@prophecy.io
language: scala
buildSystem: ''
buildSystemDetails:
  artefactID: dataprocserverlesspocscala
  parentArtefactID: shashankprophecyioteam
  buildSystem: maven
  author: null
  createdAt: '2024-09-13 09:06:28'
pipelines:
  pipelines/test_pipeline:
    name: test_pipeline
    description: ''
    author: shashank@prophecy.io
    mode: batch
    artefactID: ''
    language: scala
    createdAt: '2024-09-13 09:06:28'
    datasets:
      inputs:
      - datasets/customer_data
      outputs:
      - datasets/customer_write
    subgraphs: []
    dependencies: {}
datasets:
  datasets/customer_data:
    name: customer_data
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-09-13 09:08:00'
    mode: batch
    physicalDatasets:
      EvernorthUnityFabric:
        fabricId: 3758
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-09-13 09:08:00'
  datasets/customer_write:
    name: customer_write
    description: ''
    author: shashank@prophecy.io
    createdAt: '2024-09-13 09:10:26'
    mode: batch
    physicalDatasets:
      dev:
        fabricId: 10061
        datasetType: File
        description: ''
        author: shashank@prophecy.io
        createdAt: '2024-09-13 09:10:26'
templates: {}
jobs: {}
gemContainer:
  languageVersion: 2.12.15
  gemLibsVersion: 1.1.26
  gems: {}
  dependencies: null
functions:
  author: null
  createdAt: '2024-09-13 09:06:28'
  udfs: {}
  udafs: {}
  expressions: {}
  airflowFunctions: {}
  businessRules: {}
subgraphs: {}
sqlModels: {}
sqlSnapshots: {}
sqlTests: {}
sqlMacros: {}
sqlSeeds: {}
sqlSources: {}
sqlUnreferencedSources: {}
sqlPipeline: null
dependencies:
- modifiedAt: '2024-09-13T09:06:28.382287Z'
  name: plibMaven
  version: 8.0.31
  id: '448962362'
  createdAt: '2024-09-13T09:06:28.382287Z'
  type: plibMaven
projectDependencies:
  '12651':
    projectUID: 12651
    projectName: ProphecySparkBasicsScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12651.git&subPath=
    version: 0.2.5.5
    isDefault: true
    author: null
    createdAt: '2024-09-13 09:06:11'
  '12652':
    projectUID: 12652
    projectName: ProphecyWarehouseScala
    repositoryPath: gitUri=http://gitserver:3000/DxEheDCJ_team_5751/DxEheDCJ_project_12652.git&subPath=
    version: 0.0.5
    isDefault: true
    author: null
    createdAt: '2024-09-13 09:06:11'
flags:
  shouldAddDefaultDependenciesIfAbsent: true
pipelineConfigurations: {}
